# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
    - label: Home
      title: This is the <b>first<b> menu item.
      link: homepage
      class: homepage
    - label: Blog Posts
      link: blog-posts/
      class: blogposts
      submenu:
          - label: For Subscribers
            link: subscription-posts/
            class: subsriptionsposts
    - label: Forum
      link: forum
      class: forum
    - label: Contact
      link: contact
      class: contact
    - label: Login
      link: login
      class: login
    - label: Logout
      link: logout
      class: logout      

foo: bar
